### PR TITLE
README: very minor fix to the installation script

### PR DESCRIPTION
**Pull request by luca-s**
Replace variable name from $1 to $target_dir, since target_dir is created and never used

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Please fix typo in the commit message and reformat:

```
[README] Very minor fix to the installation script
...
```

**Comment by luca-s** [comment]
done!

**Comment by gempa-jabe** [comment]
Please use brackets to state the scope of the commit: `README:` -> `[README]`. Even if you don't like this style I prefer consistency if possible. Thank you.

**Comment by luca-s** [comment]
sure, no problem. It is not that I don't like it, I simply didn't notice it.

**Pull request merged**
